AllCops:
  TargetRubyVersion: 2.5
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/rakefile'
    - 'bin/prism'
  Exclude:
    - 'bin'

Layout/LineLength:
  Max: 126

Style/RescueStandardError:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/ClassVars:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false
